POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "My product 4",
  "price": 100.0
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE5ODM2ODMsInN1YiI6IjhhMTM0MzA1LTA5YWYtNDNkOC05YjkxLWVkZDM1M2JmMDFiYyJ9.r60nMMZLkXJUzdIMfEBOMJD6vKGHzglAoimd6m-cilU

###

GET http://localhost:8000/products/28590f4b-028c-43d1-8e45-d4b4ca2c0dd8 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/28590f4b-028c-43d1-8e45-d4b4ca2c0dd8 HTTP/1.1
Content-Type: application/json

{
  "name": "My product updated",
  "price": 369.0
}

###

DELETE http://localhost:8000/products/28590f4b-028c-43d1-8e45-d4b4ca2c0dd8 HTTP/1.1
Content-Type: application/json

